<?php $guid = $block->getStoreGuid(); ?>
<script type="text/javascript" data-cfasync="false">
    var _sbparams = _sbparams || [];
    _sbparams.push({'action': 'view'});
    (function () {
        var sb = document.createElement('script');
        var fs = document.getElementsByTagName('script')[0];
        sb.type = 'text/javascript';
        sb.async = true;
        sb.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '<?php echo $this->getAssetsDomain() . '/async/preload/' . $guid . '.js' ?>';
        fs.parentNode.insertBefore(sb, fs);
    })();
</script>
