<script type="text/javascript">
    adroll_conversion_value_in_dollars = <?php echo $block->getConversionValueInDollars() ?>;
    adroll_custom_data = {"ORDER_ID": "<?php echo $block->getIncrementId() ?>"};
</script>

<img
    src="<?php echo $this->getApiUrl() ?>/magento2/pixel/success/<?php echo $block->getStoreGuid() ?>?pageurl=<?php echo $block->getCurrentUrl() ?>"
    style="position:absolute; visibility:hidden"></div>
