<img src="<?php echo $this->getApiUrl() ?>/magento2/pixel/view?guid=<?php echo $block->getStoreGuid() ?>&pageurl=<?php echo $block->getCurrentUrl() ?>&sku=<?php echo $block->getSku() ?>" style="position:absolute; visibility:hidden"></div>
<script type="text/javascript">
	var springbot_product_info = {
		id: "<?php echo $block->getId() ?>",
		name: "<?php echo $block->getName() ?>",
		sku: "<?php echo $block->getSku() ?>"
	};
</script>
